### ISSUE TITLE
APIの呼び出し時間が長すぎる問題を修正

### ISSUE THREAD

**Issue by sayyyyyy** [sayyyyyy/IdeaHelper#26]
## 概要
OpenAI APIの呼び出しに5秒ほどかかってしまっているのでそれを改善する

## タスク
- [x] 問題の調査
- [x] 別策の提案
- [ ] 別策の実装

**Comment by yoshpy-dev** [comment]
## 原因
> OpenAI APIの利用者の報告によると、GPT-3は1分間におよそ150単語しか生成しないとされています。（これは機械翻訳ライブラリと比較すると2000倍近く遅いとされます）そのため修正することにも大きな時間がかかるため、ユーザー体験は著しく損なわれると考えられます。
[引用元](https://deepsquare.jp/2020/08/gpt-3/)

> 1,750億のパラメーターモデルは、GPUに配置して展開するには大きすぎるモデルです。「GPT-3」が実際にOpenAIのサーバーにどのように展開されているか、およびどの程度拡張できるかは誰にもわかりません。
OpenAIのCTOであるGreg Brockman氏は、7月後半にファインチューニング機能を追加することをほのめかしており、この問題の解決に役立つ可能性があります。
[引用元](https://news.ycombinator.com/item?id=23725834)

**Comment by yoshpy-dev** [comment]
## 解決策の提案
- ユーザにテキストを入力してもらう形ではなく、あらかじめこちら側からリクエストを提案して、それぞれでバックグラウンド処理を実装する。（自由度・利便性を犠牲にする。）
- GPT-3のモデルを一段階下げて、性能を犠牲にする。
- 事前にchatGPTの回答を大量に生成しておく→ユーザのリクエストの回答として最もニュアンス近い感じの回答をその場しのぎで返す→この間にバックグラウンドでAPI叩く→ユーザが回答に納得しない場合、再度アイデアを提案する形で、生成しておいたGPTの回答を返す。（時間稼ぎ）

最後の案は[サロンくんからの案](https://discord.com/channels/970243497217097778/998823715351576577/1074950484336582676)です。
ただ、最もニュアンスが近い回答を抽出する箇所の実装が大変そう。

**Comment by yoshpy-dev** [comment]
## AIモデルの変更について
現在使用されているモデルが`text-davinci-003`というもので最上位のモデルで高機能で低速。
その他、`text-curie-001`，`text-babbage-001`，`text-ada-001`があるらしいです。
モデル変更によってどのくらい性能が落ち、速度が上がるかは試してみないとわかりません。
（先輩のOpenAIアカウントからしか変更できないっぽい?）
モデルの詳細は[こちら](https://note.com/npaka/n/nef372ec2e33a#5bccbfa0-0fe3-4053-94f4-50832ba9d674)から

**Comment by sayyyyyy** [comment]
github整理のため、closeします
